### ISSUE TITLE
feat: 使用云函数替代小程序端 Request

### ISSUE THREAD

**Issue by bestony** [TaskCoding/douban#5]
**需求描述**

使用云函数发送 request ，而不是使用小程序端的 request

使用此方式屏蔽掉你小程序的域名请求限制。

**Comment by wxcloudbase** [comment]
用云函数替换掉后，返回的数据形式和wx.request的形式不同。需要将云函数返回值res.result.*重新封装成res.data.*的形式，以适应调用者的代码。
是否需要变更其他调用函数的代码逻辑？这相当于有很大的工作量
